#ifndef QLIBAPPLICATION_GLOBAL_H
#define QLIBAPPLICATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QLIBAPPLICATION_LIBRARY)
#  define QLIBAPPLICATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QLIBAPPLICATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QLIBAPPLICATION_GLOBAL_H
